version: '3.8'

services:
  web:
    build: .
    container_name: Zidan_101032330180
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      - ./ssl:/etc/apache2/ssl
    networks:
      clo2_network:
        ipv4_address: 192.168.100.180
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: DB_Zidan_101032330180
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tugas_clo2
      MYSQL_USER: zidan
      MYSQL_PASSWORD: zidanpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - clo2_network

networks:
  clo2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24